### PR TITLE
Specify easier and valid user-friendly address

### PR DESCRIPTION
**Pull request by marcullo**
After using `*.onemeter.com` subdomain, the browser is redirected to
https (related to cookies?) because we have HSTS.

Address: `onemeter-gateway.com`

### CODE REVIEW

**Comment by bbbenji** [comment]
Maybe we should add `address=/#/10.0.0.1`.
That way any domain (without strict HSTS or not previously visited) will work.

**Comment by iudex-** [comment]
wait wait wait, it looks like i could remove `hsts-include-subdomains: "true"`, but i need to figure out the implications of that.

Anyhow, if we go with the current solution i think we should not use a valid domain we don't control...
How about `onemeter.local` or something like that?

**Comment by marcullo** [comment]
okay, will change it to `onemeter.local`. Without the http prefix, some phones may interpret it as google query

**Comment by iudex-** [comment]
To finish this topic:
Even thought we could set `hsts-include-subdomains: "false"` it would be ignored by most browser as `*onemeter.com` is on the [hsts preload list](https://hstspreload.org/?domain=foo.onemeter.com) (for a while now)
While it's possible to remove the domain there, it [would take a while:](https://hstspreload.org/removal/)
>Please note that a preload list domain removal may take 6-12 weeks to reach most Chrome users, and may take longer for other browsers.

I think sticking with `onemeter.local` is fine. HSTS preload is a desirable feature, including all subdomains is a net positive.

**Pull request merged**
